### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by chozelinek** [interrogator/wwc#14]
It would be good to license the materials under some kind of license.
We have been discussing the possibility of using CC-BY. However, we have materials derived from the resbaz repo, that were released under CC-BY-SA according to @interrogator.

We only have to decide if we do the whole repo CC-BY-SA (and we keep compatible with Australia) or we license tutorials on individual basis (CC-BY for new materials and CC-BY-SA for the derivative work). If we go for the second we can register everything in a LICENSE.md file. Although it will be less work to license everything as CC-BY-SA, since viral licenses for tutorials are not bad after all.

**Comment by alvations** [comment]
Hmmm, I am for any license without the -NC so that we don't get bitten at some point of them. I don't have a particular preference as long as it does't contain -NC =)

As for the pywarmups, they're CC0 so whoever can take and when it's in this repo, it can be under CC-BY(-SA).

**Comment by interrogator** [comment]
So, is there anything wrong with a blanket CC-BY-SA for the whole repo? If there's no compelling reason to depart from the original ResBaz licenses, I'd prefer not, given that it adds complexity, and that it can be hard to know what exactly is derivative. @chozelinek, if you don't want the new material under CC-BY-SA, can you explain why?

**Comment by chozelinek** [comment]
CC-BY-SA is fine for me! I don't want to update the LICENSE.md any time we add something to the repo.

**Comment by chozelinek** [comment]
What about this? https://github.com/chozelinek/wwc/blob/license/LICENSE.md

**Comment by interrogator** [comment]
Looks good to me. Hyperlink our usernames to our profiles and submit a PR :)

**Comment by chozelinek** [comment]
Usernames linked to GitHub profiles and PR submitted!
